# Generated by Django 3.1.13 on 2021-09-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0005_auto_20210901_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_on',
        ),
    ]
