# Generated by Django 3.1.13 on 2021-09-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0008_auto_20210901_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='No comment', max_length=140),
        ),
    ]
