# Generated by Django 3.1.13 on 2021-09-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0010_auto_20210906_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
    ]
