# Generated by Django 3.1.13 on 2021-10-02 20:29

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0012_auto_20210907_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='markDownBody',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(related_name='blogposts', to='blogposts.Tag'),
        ),
    ]
